theme: jekyll-theme-minimal
title: The Learning Curves
email: uft1905@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
   Welcome to my blog site.
baseurl: "/my_blog" # the subpath of your site, e.g. /blog
url: "https://thelearningcurves.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:  thefatbuddha_
github_username:  thelearningcurves
